---

- name: Install and set keepalived
  become: yes
  gather_facts: yes
  become_method: sudo
  any_errors_fatal: true
  hosts: PGSQL_SERVERS
  vars_files:
    - vars/.secret.yml
    - vars/setup.yml

  roles:
    - role: keepalived