---

- name: Deploy postgres
  become: yes
  gather_facts: yes
  become_method: sudo
  any_errors_fatal: true
  hosts: PGSQL_SERVERS
  vars_files:
    - vars/.secret.yml
    - vars/postgres.yml
    - vars/setup.yml

  pre_tasks:
    - name: Include OS-specific variables
      include_vars: "vars/{{ ansible_os_family }}.yml"

  roles:
    - role: sysctl
    - role: limits
    - role: postgres
      when: is_install_postgres|bool

    - role: partition
      when: is_create_partition|bool
      
    - role: mount
      when: not is_restore_cluster|bool
      