---

- name: Setup pro_backup
  become: yes
  gather_facts: yes
  become_method: sudo
  any_errors_fatal: true
  hosts: backups
  vars_files:
    - vars/.secret.yml
    - vars/postgres.yml
    - vars/setup.yml

  pre_tasks:
    - name: Include OS-specific variables
      include_vars: "vars/{{ ansible_os_family }}.yml"

  roles: 
    - pg_probackup

