---

- name: Deploy vip-manager
  become: yes
  gather_facts: yes
  become_method: sudo
  any_errors_fatal: true
  hosts: PGSQL_SERVERS
  vars_files:
    - vars/.secret.yml
    - vars/setup.yml
    - vars/vip-manager.yml

  pre_tasks:
    - name: Include OS-specific variables
      include_vars: "vars/{{ ansible_os_family }}.yml"

  roles:
    - role: vip_manager