---
is_home_tests: true
is_sshkey_add: true
is_create_partition: true
is_install_postgres: true
is_standalone_cluster: false
is_install_patroni: true
is_install_etcd: true
is_install_haproxy: false
is_probackup_install: false
is_pgbouncer_install: true
is_standby_cluster: false
is_keepalived_install: false
is_install_vip: true
is_passwd_change: true

cluster_vip: "192.168.122.57"
vip_manager_mask: "24"

data_disk: "/dev/vdb"
data_part_disk: "/dev/vdb1"

patroni_cluster_name: "learning"

postgresql_change_parameters:
  - { option: "max_connections", value: "100" }
  - { option: "shared_buffers ", value: "1536MB" }
  - { option: "effective_cache_size ", value: "4GB" }
  - { option: "maintenance_work_mem", value: "320MB" }  # please change this value
  - { option: "wal_buffers", value: "8MB" }
  - { option: "wal_keep_size", value: "1GB" }
  - { option: "work_mem", value: "8MB" }  # please change this value
  - { option: "min_wal_size", value: "1GB" }
  - { option: "max_wal_size", value: "4GB" }  # or 16GB/32GB
  - { option: "huge_pages", value: "off" } 
  - { option: "max_worker_processes", value: "4" }
  - { option: "max_parallel_workers", value: "4" }
  - { option: "max_parallel_workers_per_gather", value: "2" }
  - { option: "max_parallel_maintenance_workers", value: "2" }
  - { option: "autovacuum", value: "on" }  # never turn off the autovacuum!
  - { option: "autovacuum_max_workers", value: "3" }
  - { option: "autovacuum_vacuum_scale_factor", value: "0.08" }  # or 0.005/0.001
  - { option: "autovacuum_analyze_scale_factor", value: "0.08" }
  - { option: "autovacuum_vacuum_cost_limit", value: "500" }  # or 1000/5000
  - { option: "autovacuum_vacuum_cost_delay", value: "2" }
  - { option: "autovacuum_naptime", value: "15s" }
  - { option: "autovacuum_vacuum_threshold", value: "20" }
  - { option: "wal_writer_delay ", value: "200ms" }
  - { option: "wal_writer_flush_after ", value: "1MB" }
  - { option: "random_page_cost", value: "1.25" }  # "1.1" for SSD storage. Also, if your databases fits in shared_buffers
  - { option: "effective_io_concurrency", value: "200" }  # "200" for SSD stora