---
- name: Start patroni service on Replica servers
  systemd:
    daemon_reload: true
    name: patroni
    state: started
    enabled: true
 # notify: "listen_port"

- name: "Wait for port {{ patroni_restapi_port }} to become open on the host"
  wait_for:
    port: "{{ patroni_restapi_port }}"
    host: "{{ hostvars[inventory_hostname].ansible_facts.default_ipv4.address }}"
    state: started
    timeout: 120
    delay: 20
  ignore_errors: false

- name: Check that the patroni is healthy on the replica server
  uri:
    url: "http://{{ hostvars[inventory_hostname].ansible_facts.default_ipv4.address }}:{{ patroni_restapi_port }}/health"
    status_code: 200
  register: replica_result
  until: replica_result.status == 200
  retries: 10 
  delay: 5