---
- name: create replication slot for standby cluster
  become: true
  become_user: postgres
  command: "{{ postgresql_bin_dir }}/psql -p {{ patroni_standby_cluster.port }} -h {{ patroni_standby_cluster.host }} -c 'select pg_create_physical_replication_slot('{{ patroni_standby_cluster.primary_slot_name }}')'"
  register: psql_reload_result
  changed_when: psql_reload_result.rc == 0
  failed_when: false  