---
dest_files_folder: /tmp/ansible/

# Дефолтный пользователь, заведенный при развертывании вм.
ansible_user: user
ansible_password: "pass" ## root home
#ansible_become_pass: "pass"

new_ansible_password: "pass" 
new_root_password: "pass"

postgres_os_password: "pass" 
postgres_pass: "pass"

replicator_pass: "replicator"
rewind_pass: "rewind"


create_users:
  - {username: user1,  user_password: "pass1",  create_home: true, groups: sudo, sudoers: true, nopasswd: true ,commands: "ALL"}
  - {username: user2, user_password: "pass2", create_home: true, groups: sudo, sudoers: true, nopasswd: true ,commands: "ALL"}
                                          
ssh_keys_users:
  - {username: user1, key: ""}
  - {username: user2, key: ""}
   


