---
- name: Create a new primary partition
  parted:
    device: "{{ data_disk }}"
    number: 1
    state: present

- name: Create filesystem on "{{ data_part_disk }}"
  filesystem:
    fstype: "{{ data_disk_fstype }}"
    dev: "{{ data_part_disk }}" 



    