---

- name: Change sysctl paramaters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop: "{{ sysctl_conf }}"
  ignore_errors: true
