---

- name: Install keepalived packages
  package:
    name: keepalived
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3

- name: Make sure the kernel parameters "net.ipv4.ip_nonlocal_bind", "net.ipv4.ip_forward" are enabled
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
    state: present
    reload: true
  loop:
  - "net.ipv4.ip_nonlocal_bind"
  - "net.ipv4.ip_forward"

- name: Make sure the "/usr/libexec/keepalived/" directory exists
  file:
    dest: /usr/libexec/keepalived/
    state: directory
    owner: root
    group: root

- name: Make sure the "/var/log/keepalived/" directory exists
  file:
    dest: /var/log/keepalived/
    state: directory
    owner: root
    group: root

- name: Create vrrp_script "/usr/libexec/keepalived/pg_checkstatus.sh"
  template:
    src: templates/pg_checkstatus.sh.j2
    dest: /usr/libexec/keepalived/pg_checkstatus.sh
    owner: root
    group: root
    mode: "0700"

- name: Generate conf file "/etc/keepalived/keepalived.conf"
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: "restart_keepalived"