---
- name: Linux PAM limits | add or modify nofile limits
  pam_limits:
    domain: "{{ limits_user }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop: "{{ ulimits }}"
  when: set_limits is defined and set_limits|bool
