---
- name: Insert localhost
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 localhost {{ ansible_hostname }} "


- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: '{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}'
    state: present
  with_items: '{{ groups["all"] }}'
